server:
  port: 8761
  servlet:
    context-path: /

spring:
  application:
    name: eureka server

eureka:
  client:
    registerWithEureka: false  # ????? Eureka ????????????
    fetchRegistry: false        # ???? Eureka ?????????????????????
  instance:
    hostname: eureka server     # ?? Eureka ???????
    preferIpAddress: true       # ??????? IP ???????????
    ip-address: 127.0.0.1       # ???? Eureka ???? IP ??

