server:
  port: 8888  # ??????

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mkdirP/lab3-config.git  # ??????? Git ????
          searchPaths: config  # ????? Git ????????????
          default-label: main  # ???? main ??
          cloneOnStart: true  # ?????????

